_target_: src.lit_modules.lit_classifier.LitClassifier

net:
  _target_: src.architecture.mnist_classifier.Classifier
  hidden_dim: 128

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

loss_function:
  _target_: torch.nn.CrossEntropyLoss
