name: ml-env
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python
  - pip
  - pytorch==1.12.1
  - torchvision==0.13.1
  - torchaudio==0.12.1
  - pytorch-lightning
  - hydra-core
  - mlflow
